name: main-workflow

env: 
  IMAGE_REPOSITORY: busser/foobar
  KUBECTL_VERSION: "1.14.10"
  KUSTOMIZE_VERSION: "3.5.4"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # run all unit tests.
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull requests's source code.
      - name: Check out the source code
        uses: actions/checkout@v2

      # Install Go.
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14" # The Go version to download and use.
      - name: Print Go version
        run: go version

      # Run unit tests.
      - name: Run unit tests
        run: go test -v ./...

  # Build and release.
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2

      # Build and push container image.
      - name: Build and push container image
        uses: docker/build-push-action@v5.6
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{env.IMAGE_REPOSITORY}}
          tag_with_ref: true
          tag_with_sha: true  # sha-${GITHUB_SHA::7}

  # Deploy to Kubernetes.
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - run-tests
      - build-and-release
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2

      # Set up kubectl.
      - name: Set up kubectl
        run: |-
          curl -sfLo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Configure kubectl.
      - name: Configure kubectl
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yml

      # Set up Kustomize.
      - name: Set up Kustomize
        run: |-
          curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz | tar -xzf -
          sudo mv kustomize /usr/local/bin/

      # Kustomize Kubernetes resources.
      - name: Kustomize Kubernetes resources
        working-directory: ./manifests
        run: kustomize edit set image REPOSITORY:TAG=${IMAGE_REPOSITORY}:sha-${GITHUB_SHA::7}

      # Deploy to Kubernetes.
      - name: Deploy to Kubernetes
        run: kubectl --kubeconfig kubeconfig.yml apply --kustomize manifests/

      # Validate deployment.
      - name: Validate deployment
        run: kubectl --kubeconfig kubeconfig.yml rollout status --timeout 120s deployment/foobar

